export const blips = [
  {
    id: '1',
    user: { initials: 'RK', name: 'Rohan K', color: 'pink', community: 'BITS Pilani Goa' },
    title: 'Maggi run at 11pm — who\'s in?',
    description: 'Heading to the tapri near hostel gate. Anyone awake join in!',
    tags: ['🍜 Food', 'Night owl'],
    vibe: 'food',
    category: 'college',
    joiners: 5,
    joinerInitials: ['SK', 'PL'],
    expiresIn: null,
    isLive: true,
    type: 'blip',
  },
  {
    id: '2',
    user: { initials: 'SN', name: 'Social Koramangala', color: 'teal', community: 'Koramangala' },
    title: 'Pizza & craft beer Saturday!',
    description: 'Table for 6. 4 spots left. Pay deposit to lock your seat — counts toward your bill.',
    tags: ['🍕 Food', 'Weekend'],
    vibe: 'food',
    category: 'city',
    joiners: 2,
    joinerInitials: ['AM', 'RV'],
    expiresIn: '7h',
    isLive: false,
    type: 'table',
    restaurant: 'Social — Koramangala',
    location: '4th Block, Koramangala',
    deposit: 150,
    totalSeats: 6,
    takenSeats: 2,
  },
  {
    id: '3',
    user: { initials: 'AS', name: 'Arjun S', color: 'teal', community: 'City-wide' },
    title: '5-a-side football at Cubbon Park',
    description: 'Sunday 7am. Need 4 more players. Turf booked, just show up!',
    tags: ['⚽ Sport', 'Sunday morning'],
    vibe: 'sport',
    category: 'city',
    joiners: 2,
    joinerInitials: ['MR', 'DK'],
    expiresIn: '6h',
    isLive: false,
    type: 'blip',
  },
  {
    id: '4',
    user: { initials: 'NP', name: 'Neha P', color: 'amber', community: 'Christ University' },
    title: 'Group study sesh — DSA exam prep',
    description: 'Library 2nd floor. Bring headphones. Pomodoro sessions 🍅',
    tags: ['📚 Study', 'Christ Univ'],
    vibe: 'study',
    category: 'college',
    joiners: 5,
    joinerInitials: ['TK', 'JR'],
    expiresIn: '5h',
    isLive: false,
    type: 'blip',
  },
  {
    id: '5',
    user: { initials: 'VR', name: 'Vikram R', color: 'blue', community: 'City-wide' },
    title: 'Sunset at Nandi Hills anyone?',
    description: 'Leaving from Forum Mall at 4:30pm. 3 seats in car. Petrol split.',
    tags: ['☀️ Chill', 'Road trip'],
    vibe: 'chill',
    category: 'city',
    joiners: 1,
    joinerInitials: ['SK'],
    expiresIn: '4h',
    isLive: false,
    type: 'blip',
  },
  {
    id: '6',
    user: { initials: '🎧', name: 'boAt India', color: 'amber', community: 'Sponsored' },
    title: 'Try boAt Airdopes 141 — free demo!',
    description: 'Drop by our pop-up at UB City today 3–7pm. Free trial. Lucky winners get a pair.',
    tags: ['🎁 Free event', 'UB City'],
    vibe: 'event',
    category: 'sponsored',
    joiners: 24,
    joinerInitials: ['RM'],
    expiresIn: '3h',
    isLive: false,
    type: 'sponsored',
  },
];

export const communities = [
  { id: 'c1', icon: '🎓', name: 'BITS Pilani — Goa', type: 'College · Verified', members: '2.4k', blips: 18, city: 'Goa', color: '#EEEDFE', joined: true },
  { id: 'c2', icon: '🏙️', name: 'Bengaluru — All', type: 'City-wide · Open', members: '48k', blips: 104, city: 'Bengaluru', color: '#E1F5EE', joined: true },
  { id: 'c3', icon: '⚽', name: 'Bangalore FC Fans', type: 'Interest · Open', members: '1.1k', blips: 6, city: 'Bengaluru', color: '#FAEEDA', joined: true },
  { id: 'c4', icon: '🎓', name: 'Christ University', type: 'College · Verified', members: '5.8k', blips: 31, city: 'Bengaluru', color: '#FBEAF0', joined: false },
  { id: 'c5', icon: '🎵', name: 'Indie Music Bengaluru', type: 'Interest · Open', members: '890', blips: 4, city: 'Bengaluru', color: '#E6F1FB', joined: false },
  { id: 'c6', icon: '🌍', name: 'All of India', type: 'National · Open', members: '1.2M', blips: 2100, city: 'India', color: '#E1F5EE', joined: false },
];

export const mapBlips = [
  { id: 'm1', emoji: '🍜', label: 'Maggi run', color: '#D4537E', top: '28%', left: '32%' },
  { id: 'm2', emoji: '⚽', label: 'Football', color: '#1D9E75', top: '55%', left: '62%' },
  { id: 'm3', emoji: '🍕', label: 'Table Blip', color: '#1D9E75', top: '36%', left: '68%' },
  { id: 'm4', emoji: '☀️', label: 'Nandi Hills', color: '#EF9F27', top: '68%', left: '24%' },
  { id: 'm5', emoji: '📚', label: 'Study sesh', color: '#378ADD', top: '18%', left: '58%' },
];
